# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import tictactoe_pb2 as tictactoe__pb2


class TicTacToeStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.LeaderAssignSymbols = channel.unary_unary(
                '/TicTacToe/LeaderAssignSymbols',
                request_serializer=tictactoe__pb2.SymbolsMessage.SerializeToString,
                response_deserializer=tictactoe__pb2.SymbolsResult.FromString,
                )
        self.CommandRequest = channel.unary_unary(
                '/TicTacToe/CommandRequest',
                request_serializer=tictactoe__pb2.CommandRequestMessage.SerializeToString,
                response_deserializer=tictactoe__pb2.CommandReplyResult.FromString,
                )
        self.StartGameRequest = channel.unary_unary(
                '/TicTacToe/StartGameRequest',
                request_serializer=tictactoe__pb2.StartGameRequestMessage.SerializeToString,
                response_deserializer=tictactoe__pb2.StartGameReplyResult.FromString,
                )


class TicTacToeServicer(object):
    """Missing associated documentation comment in .proto file."""

    def LeaderAssignSymbols(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CommandRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def StartGameRequest(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_TicTacToeServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'LeaderAssignSymbols': grpc.unary_unary_rpc_method_handler(
                    servicer.LeaderAssignSymbols,
                    request_deserializer=tictactoe__pb2.SymbolsMessage.FromString,
                    response_serializer=tictactoe__pb2.SymbolsResult.SerializeToString,
            ),
            'CommandRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.CommandRequest,
                    request_deserializer=tictactoe__pb2.CommandRequestMessage.FromString,
                    response_serializer=tictactoe__pb2.CommandReplyResult.SerializeToString,
            ),
            'StartGameRequest': grpc.unary_unary_rpc_method_handler(
                    servicer.StartGameRequest,
                    request_deserializer=tictactoe__pb2.StartGameRequestMessage.FromString,
                    response_serializer=tictactoe__pb2.StartGameReplyResult.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'TicTacToe', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class TicTacToe(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def LeaderAssignSymbols(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/LeaderAssignSymbols',
            tictactoe__pb2.SymbolsMessage.SerializeToString,
            tictactoe__pb2.SymbolsResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def CommandRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/CommandRequest',
            tictactoe__pb2.CommandRequestMessage.SerializeToString,
            tictactoe__pb2.CommandReplyResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def StartGameRequest(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/TicTacToe/StartGameRequest',
            tictactoe__pb2.StartGameRequestMessage.SerializeToString,
            tictactoe__pb2.StartGameReplyResult.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
